### ISSUE TITLE
Dojo do carnaval sem descrição

### ISSUE THREAD

**Issue by drazevedo** [ComputerSocietyUNB/CodingDojo#7]
Estava dando uma olhada nos problemas daqui para começar uma série de Dojos na minha empresa, e vi que o dojo do dia 25/02/2017 está sem descrição. Também parece que se necessita algum conhecimento de C# para montar o projeto, que seria bom estar descrito)

**Comment by Dayof** [comment]
@ishiikurisu tem como ver com o Rômulo a descrição do exercício e o material básico da linguagem?

**Comment by ishiikurisu** [comment]
Adicionei o README fornecido pelo mestre à edição.
